src/Entity/Job.php
<?php

namespace App\Entity;

use App\Repository\JobRepository;
use App\Utils\Jobeet as Jobeet;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=JobRepository::class)
 *
 * @ORM\Table(name ="job")
 *
 * @ORM\HasLifecycleCallbacks
 */
class Job
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

//  Assert\Choice(callback="getTypeValues")
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @Assert\NotBlank
     *
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank
     */
    private $company;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank
     */
    private $position;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank
     */
    private $location;

    /**
     * @ORM\Column(type="text")
     *
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     *
     * @Assert\NotBlank
     */
    private $how_to_apply;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_public;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_activated;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank
     *
     * @Assert\Email(
     *   message = "The email '{{ value }}' is not a valid email."
     * )
     */
    private $email;

    /**
    * @ORM\Column(type="datetime")
    */
    private $expires_at;


    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="jobs")
     *
     *@ORM\JoinColumn(name="category_id", referencedColumnName="id")
     *
     * @Assert\NotBlank
     */
    private $category;

    /**
    * @Assert\Image
    */
    public $file; // used to upload files 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getHowToApply(): ?string
    {
        return $this->how_to_apply;
    }

    public function setHowToApply(string $how_to_apply): self
    {
        $this->how_to_apply = $how_to_apply;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->is_public;
    }

    public function setIsPublic(bool $is_public): self
    {
        $this->is_public = $is_public;

        return $this;
    }

    public function getIsActivated(): ?bool
    {
        return $this->is_activated;
    }

    public function setIsActivated(bool $is_activated): self
    {
        $this->is_activated = $is_activated;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getExpiresAt(): ?\DateTimeInterface
    {
        return $this->expires_at;
    }

    public function setExpiresAt(\DateTimeInterface $expires_at): self
    {
        $this->expires_at = $expires_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

     /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
      if(!$this->getCreatedAt())
      {
        $this->created_at = new \DateTime();
      }
    }
    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
      $this->updated_at = new \DateTime();
    }

    /**
    * Slugify company attribute
    *
    * @return string 
    */
    public function getCompanySlug()
    {
        return Jobeet::slugify($this->getCompany());
    }
 
 /*
    public function getAttributeSlug($att)
    {
        if()
    } */
    // penser a factoriser ces trois fonction en une seule 
    /**
    * Slugify position attribute
    *
    * @return string
    */
    public function getPositionSlug()
    {
        return Jobeet::slugify($this->getPosition());
    }
 
    /**
    * Slugify location attribute
    *
    * @return string 
    */
    public function getLocationSlug()
    {
        return Jobeet::slugify($this->getLocation());
    }

    public static function getTypes()
    {
        return array('full-time' => 'Full time', 'part-time' => 'Part time', 'freelance' => 'Freelance');
    }

    public static function getTypeValues()
    {
      return array_keys(self::getTypes());
    }

    protected function getUploadDir()
    {
        return 'uploads/jobs';
    }
 
    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../public/vendor'.$this->getUploadDir();
    }
 
    public function getWebPath()
    {
        return null === $this->logo ? null : $this->getUploadDir().'/'.$this->logo;
    }
 
    public function getAbsolutePath()
    {
        return null === $this->logo ? null : $this->getUploadRootDir().'/'.$this->logo;
    }


    /**
     * @ORM\prePersist
     */
    public function preUpload()
    {
        if (null !== $this->file) {
            // do whatever you want to generate a unique name
            $this->logo = uniqid().'.'.$this->file->guessExtension();
        }
    }

    /**
    * @ORM\PostPersist
    */
    public function upload()
    {
        if (null === $this->file) {
            return;
        }
     
          // if there is an error when moving the file, an exception will
          // be automatically thrown by move(). This will properly prevent
          // the entity from being persisted to the database on error
          $this->file->move($this->getUploadRootDir(), $this->logo);
         
          unset($this->file);
    }
 
    /**
    * @ORM\PostRemove
    */
    public function removeUpload()
    {
        if ($file = $this->getAbsolutePath()) {
            unlink($file);
        }
    }

     /**
     * @ORM\PrePersist
     */
    public function setTokenValue()
    {
        if(!$this->getToken())
        {
            $this->token = sha1($this->getEmail().rand(11111, 99999));
        }
    }

    public function isExpired()
    {
        return $this->getDaysBeforeExpires() < 0;
    }
     
    public function expiresSoon()
    {
        return $this->getDaysBeforeExpires() < 5;
    }
     
    public function getDaysBeforeExpires()
    {
        return ceil(($this->getExpiresAt()->format('U') - time()) / 86400);
    }
}

src/Form/JobType.php
<?php

namespace App\Form;

use App\Entity\Job;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class JobType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            /*->add('type', ChoiceType::class, [
                'choices' => Job::getTypes(), 
                'expanded' => true
            ]) */
            ->add('category')
            ->add('type')
            ->add('company')
            //->add('logo',null, array('label' => 'Company logo'))
            ->add('file', FileType::class, array('label' => 'Company logo', 'required' => false))
            ->add('url')
            ->add('position')
            ->add('location')
            ->add('description')
            ->add('how_to_apply',null, array('label' => 'How to apply?'))
           // ->add('token')
            ->add('is_public', null, array('label' => 'Public?'))
             
            ->add('email')
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Job::class,
        ]);
    }
}

src/Controller/JobController.php
<?php

namespace App\Controller;

use App\Entity\Job;
use App\Form\JobType;
use App\Repository\JobRepository;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Doctrine\Persistence\ObjectManager;

/**
 * @Route("/job")
 */
class JobController extends AbstractController
{
    /**
     * @Route("/",
     *        name="job_index", 
     *        methods={"GET"}
     *  )
     */
    public function index(JobRepository $jobRepository, CategoryRepository $categoryRepository, PaginatorInterface $paginator, Request $request): Response
    {
     
        $categories = $categoryRepository->getWithJobs();
        foreach($categories as $category)
        {
            /* $category->setActiveJobs($jobRepository->getActiveJobs($category->getId(), $this->getParameter('max_jobs_on_homepage'))); */

            $query = $jobRepository->getActiveJobsQuery($category->getId());
            $pagination = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

            $category->setMoreJobs($jobRepository->countActiveJobs($category->getId()),$this->getParameter('max_jobs_on_homepage'));
        }
        return $this->render('job/index.html.twig', [
        'categories' => $categories,
        'pagination' => $pagination]);
        
    }

    /**
     * @Route("/new", 
     *         name="job_new", 
     *         methods={"GET","POST"}
     *  )
     */
    public function new(Request $request): Response
    {
        $job = new Job();
        $form = $this->createForm(JobType::class, $job);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager = $this->getDoctrine()->getManager();//to do with injection
            //$job->file->move(__DIR__.'/../../../../public/vendor/uploads/jobs', $job->file->getClientOriginalName());

           

            //$job->setLogo($job->file->getClientOriginalName());
            $job->setExpiresAt(new \DateTime('2021-11-10'));

           $manager->persist($job);
            $manager->flush();

        return $this->redirect($this->generateUrl('job_preview', [
                'company' => $job->getCompanySlug(),
                'location' => $job->getLocationSlug(),
                'token' => $job->getToken(),
                'position' => $job->getPositionSlug()
        ],UrlGeneratorInterface::ABSOLUTE_URL));

        }

        return $this->render('job/new.html.twig', [
            'job' => $job,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{company}/{location}/{id}/{position}", 
     *         name="job_show", 
     *         methods={"GET"},
     *         requirements={"id"="\d+"}
     *  )
     */
    public function show($id, JobRepository $jobRepository): Response
    {
        $job  =  $jobRepository->getActiveJob($id);
        if (!$job) {
        throw $this->createNotFoundException('Unable to find Job entity.');
        }
        // $deleteForm = $this->createDeleteForm($id);
        return $this->render('job/show.html.twig', [
            'job' => $job
        ]);
    }

   /* public function show(Job $job): Response
    {
        return $this->render('job/show.html.twig', [
            'job' => $job,
        ]);
    }*/

    /**
     * @Route("/{token}/edit", 
     *          name="job_edit", 
     *          methods={"GET","POST"}
     *  )
     */
    public function edit(Request $request, $token,JobRepository $jobRepository): Response
    {

        $job  =  $jobRepository->findOneByToken($token);
        if (!$job) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }

        $form = $this->createForm(JobType::class, $job);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();



            return $this->redirect($this->generateUrl('job_show', [
                'company' => $job->getCompanySlug(),
                'location' => $job->getLocationSlug(),
                'id' => $job->getId(),
                'position' => $job->getPositionSlug()
        ],UrlGeneratorInterface::ABSOLUTE_URL));


           // return $this->redirectToRoute('job_index');
        }

        return $this->render('job/edit.html.twig', [
            'token' => $job->getToken(),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{token}/delete", 
     *          name="job_delete", 
     *          methods={"POST"}
     *  )
     */
    public function delete(Request $request, $token): Response
    {
        $form = $this->createDeleteForm($token);
        $form->handleRequest($request);

    if ($form->isValid()) {
        $em = $this->getDoctrine()->getManager();
        $job = $em->getRepository(Job::class)->findOneByToken($token);
     
        if (!$job) {
          throw $this->createNotFoundException('Unable to find Job entity.');
        }
     
        $em->remove($job);
        $em->flush();
      }
 
  return $this->redirect($this->generateUrl('job_index'));


        /*if ($this->isCsrfTokenValid('delete'.$job->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($job);
            $entityManager->flush();
        }

        return $this->redirectToRoute('job_index');*/
    }

    /**
     * @Route("/{company}/{location}/{token}/{position}", 
     *         name="job_preview", 
     *         methods={"GET"},
     *         requirements={"token":"\w+"}
     *  )
     */
    public function previewAction($token)
    {
        $em = $this->getDoctrine()->getManager();
    
        $job = $em->getRepository(Job::class)->findOneByToken($token);
    
        if (!$job) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }
    
        $deleteForm = $this->createDeleteForm($job->getToken());
    
        return $this->render('job/show.html.twig', array(
            'job'      => $job,
            'delete_form' =>$deleteForm->createView()
        ));
    }

    private function createDeleteForm($token)
    {
      return $this->createFormBuilder(array('token' => $token))
        ->add('token')
        ->getForm()
      ;
    }
}

templates/job/_delete_form.html.twig
<form method="post" action="{{ path('job_delete', {'id': job.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ job.id) }}">
    <button class="btn">Delete</button>
</form>

templates/job/_form.html.twig
{# render the start tag and change the submission method #}
{#{{ form_start(form, {'method': 'GET','action':"path('job_create')"}) }} #}
{{ form_start(form) }}
    <table id="job_form">
      <tfoot>
        <tr>
          <td colspan="2">
            <input type="submit" value="Preview your job" />
          </td>
        </tr>
      </tfoot>
      <tbody>
        <tr>
          <th>{{ form_label(form.category) }}</th>
          <td>
            {{ form_errors(form.category) }}
            {{ form_widget(form.category) }}
          </td>
        </tr>
        <tr>
          <th>{{ form_label(form.type) }}</th>
          <td>
            {{ form_errors(form.type) }}
            {{ form_widget(form.type) }}
          </td>
        </tr>
        <tr>
          <th>{{ form_label(form.company) }}</th>
          <td>
            {{ form_errors(form.company) }}
            {{ form_widget(form.company) }}
          </td>
        </tr>
        <tr>
          <th>{{ form_label(form.file) }}</th>
          <td>
            {{ form_errors(form.file) }}
            {{ form_widget(form.file) }}
          </td>
        </tr>
        <tr>
          <th>{{ form_label(form.url) }}</th>
          <td>
            {{ form_errors(form.url) }}
            {{ form_widget(form.url) }}
          </td>
        </tr>
        <tr>
          <th>{{ form_label(form.position) }}</th>
          <td>
            {{ form_errors(form.position) }}
            {{ form_widget(form.position) }}
          </td>
        </tr>
        <tr>
          <th>{{ form_label(form.location) }}</th>
          <td>
            {{ form_errors(form.location) }}
            {{ form_widget(form.location) }}
          </td>
        </tr>
        <tr>
          <th>{{ form_label(form.description) }}</th>
          <td>
            {{ form_errors(form.description) }}
            {{ form_widget(form.description) }}
          </td>
        </tr>
        <tr>
          <th>{{ form_label(form.how_to_apply) }}</th>
          <td>
            {{ form_errors(form.how_to_apply) }}
            {{ form_widget(form.how_to_apply) }}
          </td>
        </tr>
        
        <tr>
          <th>{{ form_label(form.is_public) }}</th>
          <td>
            {{ form_errors(form.is_public) }}
            {{ form_widget(form.is_public) }}
            <br /> Whether the job can also be published on affiliate websites or not.
          </td>
        </tr>
        <tr>
          <th>{{ form_label(form.email) }}</th>
          <td>
            {{ form_errors(form.email) }}
            {{ form_widget(form.email) }}
          </td>
        </tr>
      </tbody>
    </table>
 
    {{ form_rest(form) }}
  {{ form_end(form) }}

templates/job/_list.html.twig
<table class="jobs">
    {% for job in pagination %}
        <tr {% if loop.index is odd %}class="color"{% endif %}>
            <td class="location">{{ job.location }}</td>
            
            <td class="position">
                <a href="{{ path('job_show', { 'id': job.id, 'company': job.companyslug, 'location': job.locationslug, 'position': job.positionslug }) }}">
                {{ job.position }}
                </a>
            </td>
            <td class="company">{{ job.company }}</td>
        </tr>
    {% endfor %}
</table>
{# display navigation #}
<div class="navigation">
    {{ knp_pagination_render(pagination) }}
</div>

templates/job/admin.html.twig
{# /src/Ens/JobeetBundle/Resources/views/Job/admin.html.twig #}
 
<div id="job_actions">
  <h3>Admin</h3>
  <ul>
    {% if not job.isActivated %}
      <li><a href="{{ path('job_edit', { 'token': job.token }) }}">Edit</a></li>
      <li><a href="{{ path('job_edit', { 'token': job.token }) }}">Publish</a></li>
    {% endif %}
    <li>
      <form action="{{ path('job_delete', { 'token': job.token }) }}" method="post">
        {{ form_widget(delete_form) }}
        <button type="submit" onclick="if(!confirm('Are you sure?')) { return false; }">Delete</button>
      </form> 
    </li>
    {% if job.isActivated %}
      <li {% if job.expiresSoon %} class="expires_soon" {% endif %}>
        {% if job.isExpired %}
          Expired
        {% else %}
          Expires in <strong>{{ job.getDaysBeforeExpires }}</strong> days
        {% endif %}
 
        {% if job.expiresSoon %}
          - <a href="">Extend</a> for another 30 days
        {% endif %}
      </li>
    {% else %}
      <li>
        [Bookmark this <a href="{{ url('job_preview', { 'token': job.token, 'company': job.companyslug, 'location': job.locationslug, 'position': job.positionslug }) }}">URL</a> to manage this job in the future.]
      </li>
    {% endif %}
  </ul>
</div>

templates/job/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %} New Job {% endblock %}

{% form_theme form _self %}
 
{% block field_errors %}
{#{% spaceless %} #}
  {% if errors|length > 0 %}
    <ul class="error_list">
      {% for error in errors %}
        <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{#{% endspaceless %}#}
{% endblock field_errors %}
 
{% block stylesheets %}
	  {{ parent() }}
	  <link rel="stylesheet" href="{{ asset('vendor/css/job.css') }}" type="text/css" media="all" />
{% endblock %}
 
{% block content %}
  	<h1>Job creation</h1>
    {{ include('job/_form.html.twig') }}

    <a href="{{ path('job_index') }}">back to list</a>
{% endblock %}

templates/job/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}
    Job index
{% endblock %}

{% block stylesheets %}
  {{ parent() }}
  <link rel="stylesheet" href="{{ asset('vendor/css/jobs.css') }}" type="text/css" media="all" />
{% endblock %}

{% block content %}
  <div id="jobs">
    {% for category in categories %}
     <div class="category_{{ category.slug }}">
        <div class="category">
          <div class="feed">
            <a href="">Feed</a>
          </div>
          <h1><a href = "{{path('category_show', {'slug':category.getSlug()})}}">{{ category.name }} </a></h1>
        </div>
         {% include 'job/_list.html.twig' with {'jobs': category.activejobs} %}  

        {% if category.morejobs %}
            <div class="more_jobs">
              and <a href="{{ path('category_show', { 'slug': category.slug() }) }}">{{ category.morejobs }}</a>
              more...
            </div>
        {% endif %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/job/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %} New Job {% endblock %}

{% form_theme form _self %}
 
{% block field_errors %}
{#{% spaceless %} #}
  {% if errors|length > 0 %}
    <ul class="error_list">
      {% for error in errors %}
        <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{#{% endspaceless %}#}
{% endblock field_errors %}
 
{% block stylesheets %}
	  {{ parent() }}
	  <link rel="stylesheet" href="{{ asset('vendor/css/job.css') }}" type="text/css" media="all" />
{% endblock %}
 
{% block content %}
  	<h1>Job creation</h1>
    {{ include('job/_form.html.twig') }}

    <a href="{{ path('job_index') }}">back to list</a>
{% endblock %}

templates/job/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}
    {{ job.company }} is looking for a {{ job.position }}
{% endblock %}
 
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('vendor/css/job.css') }}" type="text/css" media="all" />
{% endblock %}
 
{% block content %}
{#{{app.request.get('token')}}#}
   {% if app.request.get('token') %}
    {% include 'job/admin.html.twig' with {'job': job} %}
  {% endif %}

    <div id="job">
      <h1>{{ job.company }}</h1>
      <h2>{{ job.location }}</h2>
      <h3>
        {{ job.position }}
        <small> - {{ job.type }}</small>
      </h3>
 
      {% if job.logo %}
        <div class="logo">
          <a href="{{ job.url }}">
            <img src="/uploads/jobs/{{ job.logo }}"
              alt="{{ job.company }} logo" />
          </a>
        </div>
      {% endif %}
 
      <div class="description">
        {{ job.description|nl2br }}
      </div>
 
      <h4>How to apply?</h4>
 
      <p class="how_to_apply">{{ job.howtoapply }}</p>
 
      <div class="meta">
        <small>posted on {{ job.createdat|date('m/d/Y') }}</small>
      </div>
 
      <div style="padding: 20px 0">
        <a href="{{ path('job_edit', { 'token': job.token }) }}">
          Edit
        </a>
      </div>
    </div>
{% endblock %}